Ticket 4 completed
Sto23r12/BE-Games-Review-Project pull request #5
Opened 2023-05-11 12:11 UTC by Sto23r12

2023-05-11 14:46 UTC, MKD01 requested changes
Good work so far, but there are a few things to change/add, once you have made all your changes push them up to this branch and then re-submit a review request via /nchelp pr

2023-05-11 14:46 UTC, MKD01 commented on __tests__/api.test.js
> +          expect(input).toMatchObject(expectedOutput);
What is this testing for?

2023-05-11 14:46 UTC, MKD01 commented on __tests__/api.test.js
> +          expect(typeof review.votes).toBe("number");
This should include all properties. You can see a list of the expected properties in your ticket on trello

2023-05-11 14:46 UTC, MKD01 commented on __tests__/api.test.js
> +        response.body.review.forEach((review) => {
Should review be an array?

2023-05-12 09:15 UTC, Beth-McCormack approved these changes

2023-05-12 10:01 UTC, merged