5
Sto23r12/BE-Games-Review-Project pull request #6
Opened 2023-05-11 15:25 UTC by Sto23r12

2023-05-11 15:48 UTC, leekli requested changes
Well done so far, Charlie!

Got a couple of change requests which are outlined in my comments, the 2 main ones are:
* adding a .length check to the test
* you need a test to check that the reviews are sorted by date in descending order - see my comments on this

And any other minor changes.

Please review these, make the necessary changes and then submit a new pull request for review.

2023-05-11 15:48 UTC, leekli commented on __tests__/api.test.js
> +        response.body.reviews.forEach((review) => {
I would recommend an assertion above the .foreach to check the length of the array, to check /api/reviews gives you the exact number of reviews you are expecting to see

2023-05-11 15:48 UTC, leekli commented on __tests__/api.test.js
> +          );
No need to test against the endpoints.json file, your earlier tests on the /api endpoint should hopefully have sorted that for you

2023-05-11 15:48 UTC, leekli commented on api/app.controller.js
> +      response.status(200).send({ reviews: review });
Good use of the `reviews` key name to represent sending all reviews back

2023-05-11 15:48 UTC, leekli commented on api/app.models.js
> +  }
You're not required to implement this yet

2023-05-11 15:48 UTC, leekli commented on __tests__/api.test.js
>  });
There is 1 test missing, which is to check that `the articles should be sorted by date in descending order.` as the Trello ticket says.

You'll need to add a test for this. The 'jest-sorted' package will help you with this

2023-05-11 15:48 UTC, leekli commented on api/app.models.js
> +      "SELECT r.review_id, r.title, r.category, r.designer, r.owner, r.review_img_url, r.created_at, r.votes, COUNT(c.comment_id) AS comment_count FROM reviews AS r LEFT JOIN comments AS c ON r.revie
Nice sql query, good to see you've used the COUNT aggregate function to help you count the comments, well done!

2023-05-12 09:31 UTC, Beth-McCormack approved these changes

2023-05-12 10:01 UTC, merged